apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: node-app
      env: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: node-app
        env: dev
    spec:
      containers:
      - name: node-app
        image: jinyungxendit/node-app:1.1
        ports:
        - containerPort: 8080
