apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: NodePort
  selector:
    app: node-app
    env: dev
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 8080
    targetPort: 8080
