apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test
      env: dev
  template:
    metadata:
      labels:
        app: nginx-test
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.10
        ports:
        - containerPort: 80
