apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  type: NodePort
  selector:
    app: nginx
    env: dev
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 80
    targetPort: 80
